name: RandomTP
main: fr.k0bus.randomtp.Main
version: 0.2
api-version: 1.14
commands:
   randomtp:
      description: Teleportation aleatoire sur la map
      usage: /randomtp <distance>
permissions:
	randomtp.bypass.cooldown:
		description: Bypass /randomtp cooldown
	randomtp.bypass.timer:
		description: Bypass teleport delay